name: Code quality

on: [push]

env:
  in-depth-python-version: "3.11"

jobs:

  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.in-depth-python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.in-depth-python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Analysing the code with flake8
      run: |
        ./lint_flake8.sh

  pylint:
    needs: flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.in-depth-python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.in-depth-python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        ./lint_pylint.sh

  mypy:
    needs: pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.in-depth-python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.in-depth-python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
    - name: Static type checking with mypy
      run: |
        ./mypy.sh

  pytest:
    needs: mypy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.in-depth-python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.in-depth-python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
    - name: Unit testing with pytest
      run: |
        ./pytest.sh

  codecov:
    needs: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.in-depth-python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.in-depth-python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
    - name: Unit testing with pytest
      run: |
        ./pytest.sh
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  cqall:
    needs: pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Full code quality testing with ./cqall.sh
      run: |
        ./cqall.sh
